src/market/cart/urls.py
from django.urls import path
from . import views

app_name = 'market.cart'

urlpatterns = [
    path('', views.CartDetailsView.as_view(), name='cart_details'),
    path('add/<str:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('remove/<str:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

src/market/comparison/urls.py
from django.urls import path

from .views import AddToCompareView, RemoveFromCompareView, CompareListView

app_name = 'comparison'

urlpatterns = [
    path('add-to-compare/<int:product_id>/', AddToCompareView.as_view(), name='add_to_compare'),
    path('remove-from-compare/<int:product_id>/', RemoveFromCompareView.as_view(), name='remove_from_compare'),
    path('', CompareListView.as_view(), name='compared_products'),
]

src/market/market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.banner_app.urls')),
    path('products/', include('market.products.urls')),
    path('categories/', include('market.categories.urls')),
    path('bank/', include('market.paymentsystem.urls')),
    path('catalog/', include('market.catalog_app.urls')),
    path('profiles/', include('market.profiles.urls')),
    path('sellers/', include('market.sellers.urls')),

    # путь к приложению orders
    path('profiles/orders/', include('market.orders.urls')),

    # путь к приложению payment
    path('profiles/orders/<int:pk>/pay/', include('market.payment.urls')),

    path('cart/', include('market.cart.urls')),
    path('comparison/', include('market.comparison.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

src/market/products/urls.py
from django.contrib import admin
from django.urls import path

from market.products.views import ProductDetailView

app_name = 'products'

urlpatterns = [
    path('<slug:product_slug>/', ProductDetailView.as_view(), name='product-details'),
]

src/market/sellers/urls.py
from django.urls import path

from market.sellers.views import SellerDetailsView

app_name = 'sellers'

urlpatterns = [
    path('<slug:seller_slug>/', SellerDetailsView.as_view(), name='seller-details'),
]

src/market/products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Min, Max
from django.urls import reverse

from market.categories.models import Category


class ProductFeedback(models.Model):
    class Meta:
        ordering = [
            "user",
            "created_at",
        ]
        verbose_name = 'отзыв на продукт'
        verbose_name_plural = 'отзывы на продукт'
    user = models.ForeignKey(
        User,
        null=False,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
    )
    product = models.ForeignKey(
        'Product',
        null=False,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='Продукт',
        )
    feedback_text = models.TextField()
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name='отзыв создан',
    )

    def __str__(self):
        return f" Пользователь {self.user.username} оставил отзыв"


def image_directory_path(instance: 'Product', filename) -> str:
    return f'images/products/product_{instance.slug}/product_preview/{filename}'


class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    name = models.CharField(max_length=20, verbose_name='название')
    preview = models.ImageField(null=True, unique=True, upload_to=image_directory_path, verbose_name='изображение')
    categories = models.ManyToManyField(Category, related_name='products', verbose_name='категории')
    description = models.TextField(verbose_name='описание')
    is_active = models.BooleanField(default=True, verbose_name='активирован')
    slug = models.SlugField(max_length=20, unique=True)
    specification = models.ManyToManyField("Specification", related_name='specifications')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        preview_path = image_directory_path(self, self.preview)
        product = Product.objects.filter(preview=preview_path).first()
        if product is None:
            super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("products:product-details", kwargs={"product_slug": self.slug})

    def get_price_range(self) -> str:
        min_max = self.seller_products.aggregate(Min('price'), Max('price'))
        if min_max['price__min'] == min_max['price__max']:
            result = '{:.2f}'.format(min_max['price__min'])
        else:
            result = '{:.2f} - {:.2f}'.format(min_max['price__min'], min_max['price__max'])

        return result
    

def product_image_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=product_image_directory_path)


class ProductViewHistory(models.Model):
    class Meta:
        ordering = [
            "user",
            "product",
            "view_at",
        ]
        verbose_name = 'просмотр продукта'
        verbose_name_plural = 'просмотры продукта'
    user = models.ForeignKey(
        User,
        null=False,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name='пользователь',
    )
    product = models.ForeignKey(
        Product, null=False,
        blank=True,
        on_delete=models.CASCADE,
        related_name='product_view_history',
        verbose_name='продукт'
    )
    view_at = models.DateField(
        auto_now_add=True,
        verbose_name='дата просмотра продукта',
    )

    def __str__(self):
        return f" Пользователь {self.name} просматривал продукт {self.product} {self.view_at}."

class Specification(models.Model):
    class Characteristics(models.IntegerChoices):
        CLASS = 1, 'Class'
        MODEL = 2, 'Model'
        YEAR_RELEASE = 3, 'Year release'
        COLOUR = 4, 'Colour'
        DIAGONAL = 5, 'Diagonal'
        SCREEN_RESOLUTION = 6, 'Screen resolution'
        MATRIX = 7, 'Matrix'
        REFRASH_RATE = 8, 'Refresh rate'
        PIXEL_DENSITY = 9, 'Pixel density'
        RAM = 10, 'Ram'
        INTERNAL_MEMORY = 11, 'Internal memory'

    name = models.CharField(max_length=50)
    type = models.SmallIntegerField(choices=Characteristics.choices, default=Characteristics.MATRIX)
    value = models.TextField()

    def __str__(self):
        return f"{self.name}: {self.value}"

src/market/products/forms.py
from django.forms import ModelForm
from django.forms import Textarea
from .models import Product, ProductFeedback


class ProductFeedbackForm(ModelForm):
    class Meta:
        model = ProductFeedback
        fields = ['feedback_text']
        widgets = {
            'feedback_text': Textarea(attrs={
                "class": "form-textarea",
                "name": "review",
                "id": "review",
                "placeholder": "Отзыв"
            })
        }

src/market/products/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.views.generic import DetailView
from .forms import ProductFeedbackForm
from market.categories.mixins import MenuMixin
from market.banner_app.mixins import BannerSliderMixin
from market.products.models import Product, ProductFeedback
from market.browsing_history_app.models import ProductBrowsingHistory
import logging
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.conf import settings

from ..search_app.mixins import SearchMixin

from market.cart.cart import Cart
from market.sellers.models import SellerProduct



log = logging.getLogger(__name__)


class ProductDetailView(MenuMixin, BannerSliderMixin, DetailView, SearchMixin):
    template_name = 'products/product_details.html'
    model = Product
    context_object_name = 'product'
    slug_url_kwarg = 'product_slug'
    form_class = ProductFeedbackForm
    success_url = reverse_lazy('products:product-details')

    def get_queryset(self) -> QuerySet[Any]:
        return super().get_queryset().prefetch_related('seller_products')

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        response = super().get(request, *args, **kwargs)
        cart = Cart(request.session)
        amount = request.GET.get('amount')
        seller_product_id = request.GET.get('seller_product_id')

        if seller_product_id is None:
            product = self.get_object()
            seller_product = product.seller_products.order_by('price').first()
        else:
            seller_product = SellerProduct.objects.get(id=seller_product_id)
            amount = 1

        if amount or seller_product_id:
            cart.add(seller_product, int(amount))

        return response

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)
        if response:
            return response

        if not request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)

        form = self.form_class(request.POST)
        if form.is_valid():
            feedback_text = form.cleaned_data.get("feedback_text")
            ProductFeedback.objects.create(
                user=self.request.user,
                product=self.get_object(),
                feedback_text=feedback_text,
            )
            log.debug(f"Создан новый объект БД - отзыв на продукт. {self.get_object()} - {feedback_text}")
            return redirect(reverse(
                'products:product-details',
                kwargs={self.slug_url_kwarg: self.get_object().slug}
            ))
        return render(request, self.template_name, {'form': form})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class()
        context['product_feedbacks'] = (ProductFeedback.objects.
                                        prefetch_related('user', 'product').
                                        filter(product=self.object)
                                        )

        # Проверяем, был ли данный товар уже в списке ранее просмотренных товаров. Если нет, то добавляем
        # Если товар уже в списке, то не добавляем
        if self.request.user.is_authenticated:
            products = (ProductBrowsingHistory.objects.
                        select_related('user', 'product').
                        filter(user=self.request.user))
            product = self.get_object()
            if not products.filter(product=product).exists():
                ProductBrowsingHistory.objects.create(
                    user=self.request.user,
                    product=product,
                )
            browsing_history = (ProductBrowsingHistory.objects.
                                select_related('user', 'product').
                                filter(user=self.request.user).
                                values_list("product__name", flat=True)
                                )
            context['browsing_history'] = browsing_history

        context['product_tags'] = context['product'].tags.all()
        log.debug("Запуск рендеренга ProductDetailView")
        log.debug("Контекст для ProductDetailView готов. ")
        return context

src/market/products/templates/products/product_details.html
{% extends 'repeat_blocks.html' %}
{% load static %}

{% block title %}
  <title>Продукт</title>
{% endblock %}

{% block header-slider %}

{% endblock %}

{% block middle %}
  <div class="Section">
    <div class="wrap">
      <div class="Product">
        <div class="ProductCard">
          <div class="ProductCard-look">
            <div class="ProductCard-photo">
              <img src="{{ product.preview.url }}" alt="bigGoods.png"/>
            </div>
            <div class="ProductCard-picts">
              <a class="ProductCard-pict ProductCard-pict_ACTIVE" href="{{ product.preview.url }}"><img src="{{ product.preview.url }}" alt="bigGoods.png"/></a>
              {% for img in product.images.all %}
                <a class="ProductCard-pict" href="{{ img.image.url }}"><img src="{{ img.image.url }}" alt="{{ img.image.name }}" /></a>
              {% endfor %}
            </div>
          </div>
          <div class="ProductCard-desc">
            <div class="ProductCard-header">
              <h2 class="ProductCard-title">{{ product.name }}</h2>
              <div class="ProductCard-info">
                <div class="ProductCard-cost">
                  <div class="ProductCard-price">{{ product.get_price_range }} руб.</div>
                </div>
              </div>
            </div>
            <div class="ProductCard-text"></div>
            <form>
              <div class="ProductCard-cart">
                <div class="ProductCard-cartElement ProductCard-cartElement_amount">
                  <div class="Amount Amount_product">
                    <button class="Amount-remove" type="button">
                    </button>
                    <input class="Amount-input form-input" name="amount" type="text" value="1"/>
                    <button class="Amount-add" type="button">
                    </button>
                  </div>
                </div>
                <div class="ProductCard-cartElement">
                  <button class="btn btn_primary" type="submit">
                    <img class="btn-icon" href="{% url 'market.cart:cart_add' product.pk %}" src="{% static 'assets/img/icons/card/cart_white.svg' %}" alt="cart_white.svg"/>
                    <span class="btn-content">Купить</span>
                  </button>
                </div>
                {% if product.id not in request.session.compare_list or not request.session.compare_list  %}
                  {% if request.session.compare_list|length < 4 %}
                <div class="ProductCard-cartElement">
                  <a class="btn btn_primary" href="{% url 'comparison:add_to_compare' product.id %}">
                    <img class="btn-icon" src="{% static 'assets/img/icons/card/compare_white.svg' %}" width="23px" height="23px" alt="compare_white.svg"/>
                    <span class="btn-content">Добавить в сравнение</span>
                  </a>
                </div>
                  {% endif %}
                {% else %}
                <div class="ProductCard-cartElement">
                  <a class="btn btn_primary" href="{% url 'comparison:remove_from_compare' product.id %}">
                    <img class="btn-icon" src="{% static 'assets/img/icons/card/compare_white.svg' %}" width="23px" height="23px" alt="compare_white.svg"/>
                    <span class="btn-content">Убрать из сравнения</span>
                    <br>
                  </a>
                </div>
                {% endif %}<div id="modal_open" class="my_modal">
                  <div class="my_modal-dialog">
                    <div class="my_modal-content">
                      <div class="my_modal-header">
                        <p class="my_modal-title">Поздравляем!</p>
                        <a href="#" title="Закрыть модальное окно" class="close">×</a>
                      </div>
                      <div class="my_modal-body">
                        <p>Товар успешно добавлен в корзину!</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </form>
            <div class="ProductCard-footer">
              <div class="ProductCard-tags">
                {% if product_tags %}
                  <strong class="ProductCard-tagsTitle">Тэги:</strong>
                  {% for tag in product_tags %}
                    <a href="{% url 'market.catalog_app:catalog' %}?tag={{ tag.name }}">{{ tag.name }}</a>{% if product_tags.last != tag %},{% endif %}
                  {% endfor %}
                {% else %}
                  <span style="color: #a8aab4">У этого продукта нет тегов</span>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="Tabs Tabs_default">
          <div class="Tabs-links">
            <a class="Tabs-link_ACTIVE Tabs-link" href="#description">
              <span>Описание</span>
            </a>
            <a class="Tabs-link" href="#sellers">
              <span>Продавцы</span>
            </a>
            <a class="Tabs-link" href="#addit">
              <span>Характеристика</span>
            </a>
            <a class="Tabs-link" href="#reviews">
              <span>Отзывы ({{product_feedbacks|length}})</span>
            </a>
          </div>
          <div class="Tabs-wrap">
            <div class="Tabs-block" id="description">
              <p>{{ product.description }}</p>
              <img class="pict pict_right" src="{{ product.preview.url }}" alt="bigGoods.png"/>
              <div class="clearfix">
              </div>
              </div>
            </div>
            <div class="Tabs-block" id="sellers">
              <div class="Section-content">
                <div class="Orders">
                  <div class="Order Order_anons">
                    <div class="Order-personal">
                      {% for product in product.seller_products.all %}
                        <div class="row">
                          <div class="row-block">
                            <a class="Order-title" href="{% url 'sellers:seller-details' seller_slug=product.seller.slug %}">
                              {{ product.seller.name }}
                            </a>
                            <form>
                              <div class="ProductCard-cartElement" style="margin-top: 10px;">
                                <a class="btn btn_primary" href="?seller_product_id={{ product.pk }}#modal_open" type="sumbit">
                                  <img class="btn-icon" src="{% static 'assets/img/icons/card/cart_white.svg' %}" alt="cart_white.svg"/>
                                  <span class="btn-content">Купить</span>
                                </a>
                              </div>
                            </form>
                          </div>
                          <div class="row-block">
                            <div class="Order-info Order-info_delivery">
                              <div class="Order-infoType">Тип доставки:
                              </div>
                              <div class="Order-infoContent">Обычная доставка
                              </div>
                            </div>
                            <div class="Order-info Order-info_pay">
                              <div class="Order-infoType">Оплата:
                              </div>
                              <div class="Order-infoContent">Онлайн картой
                              </div>
                            </div>
                            <div class="Order-info">
                              <div class="Order-infoType">Стоимость:
                              </div>
                              <div class="Order-infoContent">
                              <span class="Order-price">
                                {% if product.discount.type.name != 'undiscounted' %}
                                  <span class="discounted_price">{{ product.price }} руб.</span>
                                  {{ product.get_discounted_price|floatformat:2 }} руб.
                                {% else %}
                                  {{ product.price }} руб.
                                {% endif %}
                              </span>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="Tabs-block" id="addit">
              <div class="Product-props">
                {% if product.specification.all %}
                  {% for spec in product.specification.all %}

                  <div class="Product-prop">
                    <strong>{{ spec.name }} :
                    </strong><span>{{ spec.value }}</span>
                  </div>
                  {% endfor %}
                {% else %} Характеристики не заявлены продавцом
                {% endif %}
              </div>
            </div>

            <div class="Tabs-block" id="reviews">
                <header class="Section-header">
                  <h3 class="Section-title">Количество отзывов на товар {{product}}:{{ product_feedbacks|length }}
                  </h3>
                </header>
              {% for feedback in product_feedbacks %}
                <p></p>
                <div class="Comments">
                  <div class="Comment">
                    <div class="Comment-column Comment-column_pict">
                      <div class="Comment-avatar">
                      </div>
                    </div>
                    <div class="Comment-column">
                      <header class="Comment-header">
                        <div>
                          <strong class="Comment-title">{{feedback.user.username}}
                          </strong><span class="Comment-date">{{feedback.created_at}}</span>
                        </div>
                      </header>
                      <div class="Comment-content">{{ feedback.feedback_text }}
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
                <header class="Section-header Section-header_product">
                  <h3 class="Section-title">Добавить отзыв
                  </h3>
                </header>
                <div class="Tabs-addComment">
                  <form method="post" class="form">
                    {% csrf_token %}
                    <div class="form-group">
                      {{ form.feedback_text }}
                    </div>
                    <div class="form-group">
                      <button class="btn btn_muted" type="submit">Отправить отзыв
                      </button>
                    </div>
                  </form>
                </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/market/products/templates/products/products.html
{% extends 'categories/index.html' %}

{% block title %}
  Products
{% endblock %}

{% block body %}
  <h1>Product {{ product.name }}</h1>
  {% if product.preview %}
    <p>Preview: <img src="{{ product.preview.url }}" alt="Product preview" style="width: 100px"></p>
  {% else %}
    <p>Preview: Does not exist</p>
  {% endif %}
  <p>Description: {{ product.description }}</p>
  <p>Is_active: {{ product.is_active }}</p>
{% endblock %}