src/market/cart/urls.py
from django.urls import path
from . import views

app_name = 'market.cart'

urlpatterns = [
    path('', views.CartDetailsView.as_view(), name='cart_details'),
    path('add/<str:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('remove/<str:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

src/market/comparison/urls.py
from django.urls import path

from .views import AddToCompareView, RemoveFromCompareView, CompareListView

app_name = 'comparison'

urlpatterns = [
    path('add-to-compare/<int:product_id>/', AddToCompareView.as_view(), name='add_to_compare'),
    path('remove-from-compare/<int:product_id>/', RemoveFromCompareView.as_view(), name='remove_from_compare'),
    path('', CompareListView.as_view(), name='compared_products'),
]

src/market/market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.banner_app.urls')),
    path('products/', include('market.products.urls')),
    path('categories/', include('market.categories.urls')),
    path('bank/', include('market.paymentsystem.urls')),
    path('catalog/', include('market.catalog_app.urls')),
    path('profiles/', include('market.profiles.urls')),
    path('sellers/', include('market.sellers.urls')),

    # путь к приложению orders
    path('profiles/orders/', include('market.orders.urls')),

    # путь к приложению payment
    path('profiles/orders/<int:pk>/pay/', include('market.payment.urls')),

    path('cart/', include('market.cart.urls')),
    path('comparison/', include('market.comparison.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

src/market/comparison/views.py
from django.contrib import messages
from django.contrib.postgres.aggregates import ArrayAgg
from django.http import HttpResponseRedirect
from django.views import View
from django.views.generic import TemplateView

from ..categories.mixins import MenuMixin
from ..products.models import Product
from ..search_app.mixins import SearchMixin
from ..sellers.models import SellerProduct


class CompareList:
    def __init__(self, session):
        self.session = session
        if 'compare_list' not in self.session:
            self.session['compare_list'] = []

    def add_to_compare(self, product_id: int) -> str:
        """Функция добавляет id выбранного товара в список для сравнения товаров"""
        if product_id not in self.session['compare_list'] and len(self.session['compare_list']) < 4:
            added_product = Product.objects.filter(id=product_id).first()
            if added_product is not None:
                self.session['compare_list'].append(product_id)
                message: str = f"Товар {added_product.name} добавлен в сравнение.\n"
                self.session.modified = True
                return message

    def remove_from_compare(self, product_id: int):
        """Функция удаляет id выбранного товара из списка для сравнения товаров"""
        if product_id in self.session['compare_list']:
            removed_product = Product.objects.filter(id=product_id).first()
            if removed_product is not None:
                self.session['compare_list'].remove(product_id)
                message: str = f"Товар {removed_product.name} удален из сравнения.\n"
                self.session.modified = True
                return message

    def get_compared_products(self):
        """Функция формирует queryset из товаров списка для сравнения"""
        if 'compare_list' in self.session and len(self.session['compare_list']) in range(2, 5):
            return (Product.objects.filter(id__in=self.session['compare_list'])
                    .prefetch_related("specification", "categories"))
        else:
            return []

    def get_prices_products(self):
        queryset = SellerProduct.objects.filter(
            product_id__in=self.session['compare_list'],
        ).values(
            "product_id",
        ).annotate(
            prices=ArrayAgg("price")
        ).order_by(
            "product_id",
        )
        return queryset


class AddToCompareView(MenuMixin, View):
    def get(self, request, product_id):
        compare_list = CompareList(self.request.session)
        message = compare_list.add_to_compare(product_id)
        if message is not None:
            messages.success(self.request, message)
        referer_url: str = self.request.META.get('HTTP_REFERER')
        return HttpResponseRedirect(referer_url)


class RemoveFromCompareView(MenuMixin, View):
    def get(self, request, product_id):
        compare_list = CompareList(self.request.session)
        message: str = compare_list.remove_from_compare(product_id)
        if message is not None:
            messages.success(self.request, message)
        referer_url: str = self.request.META.get('HTTP_REFERER')
        if len(self.request.session['compare_list']) == 1 and "comparison" in referer_url:
            product_id_last = self.request.session['compare_list'][0]
            compare_list.remove_from_compare(product_id_last)
        return HttpResponseRedirect(referer_url)


class CompareListView(SearchMixin, MenuMixin, TemplateView):
    template_name = 'comparison/comparison.html'

    def get_context_data(self, **kwargs):
        context = super(CompareListView, self).get_context_data(**kwargs)
        compare_list = CompareList(self.request.session)
        compared_products = compare_list.get_compared_products()
        only_categories: list = list()
        for product in compared_products:
            for category in product.categories.all():
                only_categories.append(category)
        if len(set(only_categories)) != 1:
            messages.success(self.request, "Сравниваемые между собой товары должны быть из одной категории ")
        else:
            context['different_categories'] = True
        if len(compared_products) > 0:
            prices_compared_products = compare_list.get_prices_products()
            context['prices_products'] = prices_compared_products
        if self.request.GET.get('checkbox_only_diff') == 'on':
            list_differences = create_list_differences(compared_products)
            context['checked'] = True
        else:
            list_differences = None
            context['checked'] = False
            context['list_specifications'] = create_list_specifications(compared_products)
        context['compared_products'] = compared_products
        context['list_differences'] = list_differences
        return context


def create_list_differences(compared_products: CompareList) -> list:
    """
    Функция формирует список характеристик модели Specification,
    значения которых для выбранных товаров отличаются
    """
    dict_only_diff: dict = dict()
    list_differences: list = list()
    for item in compared_products:
        for spec in item.specification.all():
            if spec.name not in dict_only_diff:
                dict_only_diff[spec.name] = []
            dict_only_diff[spec.name].append(spec.value)
    for key, value in dict_only_diff.items():
        if len(set(value)) > 1:
            list_differences.append(key)
    return list_differences


def create_list_specifications(compared_products: CompareList) -> list:
    """Функция формирует полный список характеристик модели Specification для выбранных товаров"""
    list_specifications: list = list()
    for item in compared_products:
        for spec in item.specification.all():
            list_specifications.append(spec.name)
    if len(set(list_specifications)) == len(list_specifications):
        list_specifications.clear()
    else:
        list_specifications = list(set(list_specifications))
    return list_specifications

src/market/comparison/templates/comparison/compare_add_remove.html
{% load static %}

{% if product.id not in request.session.compare_list or not request.session.compare_list  %}
  {% if request.session.compare_list|length < 4 %}
<a class="Card-btn" title="Добавить в сравнение" href="{% url 'comparison:add_to_compare' product.id %}"><img src="{% static 'assets/img/icons/card/compare.svg' %}" alt="compare.svg"/></a>
  {% endif %}
{% else %}
<a class="Card-btn" title="Убрать из сравнения" href="{% url 'comparison:remove_from_compare' product.id %}"><img src="{% static 'assets/img/icons/card/compare.svg' %}" alt="compare.svg"/></a>
{% endif %}

src/market/comparison/templates/comparison/comparison.html
{% extends 'repeat_blocks.html' %}
{% load custom_filters %}
{% load static %}

{% block title %}
  <title>Сравнение</title>
{% endblock %}

{% block header-slider %}

{% endblock %}

{% block middle %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if compared_products|length > 1 %}
<form action="{% url 'comparison:compared_products' %}" method="get">
    <span class="col-2">Только отличающиеся параметры</span>
        <label class="checkbox" for="checkbox">
          <input class="checkbox" type="checkbox" id="checkbox" name="checkbox_only_diff" {% if checked %} checked {% endif %}>
        </label>
    <button type="submit">Применить</button>
</form>
{% else %}
<div class="Middle">
    <div class="wrap">
        <div class="Product">
            <div class="ProductCard">
                <div class="ProductCard-desc">
                    <div class="ProductCard-header">
                        <div>
                            Недостаточно товаров для сравнения. Одновременно можно сравнивать от 2 до 4 товаров.
                            Предварительно выберите необходимые товары в каталоге, категориях или воспользуйтесь поиском.
                            На карточках интересующих товаров кликайте на значок
                            <img src="{% static 'assets\img\icons\card\compare.svg' %}" alt="compare.svg"/>
                            и затем переходите к сравнению товаров
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="Middle">
    <div class="wrap">
        <div class="Product">
            <div class="ProductCard">
                {% for item in compared_products %}
                <div class="ProductCard-desc">
                    <div class="ProductCard-header">
                        <h2 class="ProductCard-title">{{ item.name }}
                        </h2>
                        <div class="ProductCard-look">
                            <div class="ProductCard-photo">
                                <img src="{{ item.preview.url }}" alt="{{ item.name }}" />
                            </div>
                        </div>

                        <div class="Tabs Tabs_default">
                            <div class="Tabs-wrap">
                                <div class="Tabs-block" id="description">
                                    <div class="table">
                                        <table>
                                        {% if different_categories %}
                                        <tr>
                                            <td class="comparis">Характеристики</td>
                                        </tr>
                                            {% if list_differences %}
                                                {% for characteristic in list_differences %}
                                        <tr>
                                            <td>{{ characteristic }}</td>
                                                    {% for spec in item.specification.all %}

                                                        {% if spec.name == characteristic %}
                                            <td>{{ spec.value }}</td>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endfor %}
                                            {% else %}
                                                {% if list_specifications %}
                                                     {% for characteristic in list_specifications %}
                                            <td>{{ characteristic }}</td>
                                                            {% for spec in item.specification.all %}
                                                                {% if spec.name == characteristic %}

                                            <td>{{ spec.value }}</td>
                                                                {% endif %}
                                                            {% endfor %}
                                        </tr>
                                                    {% endfor %}
                                                {% endif %}
                                            {% endif %}
                                        {% endif %}
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                     <div class="ProductCard-cart">
                        <div class="ProductCard-cartElement">
                            <a class="btn btn_primary" href="{% url 'comparison:remove_from_compare' item.id %}">
                                <img class="btn-icon" src="{% static 'assets\img\icons\card\compare.svg' %}" alt="compare.svg"/>Удалить из сравнения
                            </a>
                        </div>
                    </div>
                    <div class="ProductCard-info">
                        <div class="ProductCard-cost">
                            {% for idx in prices_products %}
                                {% if idx.product_id == item.id %}
                            <div class="ProductCard-price">{{ idx.prices | format_array }}
                            </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="ProductCard-cart">
                        <div class="ProductCard-cartElement">
                            <a class="btn btn_primary" href="{% url 'market.cart:cart_add' item.pk %}" >
                                <img class="btn-icon" src="{% static 'assets\img\icons\card\cart_white.svg' %}" alt="cart_white.svg"/>Добавить в корзину
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}