src/market/cart/urls.py
from django.urls import path
from . import views

app_name = 'market.cart'

urlpatterns = [
    path('', views.CartDetailsView.as_view(), name='cart_details'),
    path('add/<str:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('remove/<str:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

src/market/market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.banner_app.urls')),
    path('products/', include('market.products.urls')),
    path('categories/', include('market.categories.urls')),
    path('bank/', include('market.paymentsystem.urls')),
    path('catalog/', include('market.catalog_app.urls')),
    path('profiles/', include('market.profiles.urls')),
    path('sellers/', include('market.sellers.urls')),

    # путь к приложению orders
    path('profiles/orders/', include('market.orders.urls')),

    # путь к приложению payment
    path('profiles/orders/<int:pk>/pay/', include('market.payment.urls')),

    path('cart/', include('market.cart.urls')),
    path('comparison/', include('market.comparison.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    urlpatterns.append(
        path('__debug__/', include('debug_toolbar.urls')),
    )

src/market/orders/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from . import views

app_name = 'orders'

router = DefaultRouter()
router.register('orders', views.OrderViewSet)

urlpatterns = [
    path('', views.OrdersHistoryView.as_view(), name='orders_history'),
    path('<int:pk>/', views.OrderDetailView.as_view(), name='order_details'),
    path('create/page_1/', views.MakingOrderPage1View.as_view(), name='making_an_order_page_1'),
    path('create/page_2/', views.MakingOrderPage2View.as_view(), name='making_an_order_page_2'),
    path('create/page_3/', views.MakingOrderPage3View.as_view(), name='making_an_order_page_3'),
    path('create/page_4/', views.MakingOrderPage4View.as_view(), name='making_an_order_page_4'),
    path('api/', include(router.urls)),
]

src/market/payment/urls.py
from django.urls import path

from .views import PayView

app_name = 'payment'

urlpatterns = [
    path('payment/', PayView.as_view(), name='payment'),
]

src/market/products/urls.py
from django.contrib import admin
from django.urls import path

from market.products.views import ProductDetailView

app_name = 'products'

urlpatterns = [
    path('<slug:product_slug>/', ProductDetailView.as_view(), name='product-details'),
]

src/market/orders/models.py
from django.conf import settings
from django.db import models
from django.db.models import F

from market.sellers.models import SellerProduct, DiscountType


class Order(models.Model):
    DELIVERY_METHOD_CHOICES = [
        ('ordinary', 'Обычная доставка'),
        ('express', 'Экспресс доставка')
    ]
    PAYMENT_METHOD_CHOICES = [
        ('online', 'Онлайн картой'),
        ('someone', 'Онлайн со случайного чужого счета')
    ]

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE, related_name='orders', verbose_name='пользователь')
    seller_products = models.ManyToManyField(SellerProduct, related_name='orders', verbose_name='продукты продавца')
    cost = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name='общая стоимость заказа')
    delivery_city = models.CharField(null=True, max_length=256, verbose_name='город заказчика')
    delivery_address = models.TextField(verbose_name='адрес заказчика')
    delivery_method = models.CharField(default=DELIVERY_METHOD_CHOICES[0], null=True, max_length=256, choices=DELIVERY_METHOD_CHOICES, verbose_name='способ доставки')
    payment_method = models.CharField(default=PAYMENT_METHOD_CHOICES[0], null=True, max_length=256, choices=PAYMENT_METHOD_CHOICES, verbose_name='способ оплаты')
    full_name = models.CharField(null=True, max_length=256, verbose_name='ФИО')
    phone = models.CharField(null=True, max_length=256, verbose_name='телефон')
    email = models.EmailField(null=True, verbose_name='почта')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата и время обновления заказа')
    status = models.ForeignKey('OrderStatus', null=True, on_delete=models.PROTECT, related_name='orders', verbose_name='статус заказа')
    quantity_products = models.JSONField(null=True, verbose_name='продукт заказа')
    discount_type = models.ForeignKey(DiscountType, null=True, on_delete=models.PROTECT, related_name='order', verbose_name='тип скидки')

    def __str__(self):
        return f'Заказ {self.pk}'

    def check_paid(self):
        return self.status.value == 'paid'

    def get_products(self):
        products_ids = self.quantity_products.keys()
        return SellerProduct.objects.filter(pk__in=products_ids)

    def change_stock(self):
        quantity_products = self.quantity_products
        for seller_product in self.get_products():
            seller_product.stock -= quantity_products[str(seller_product.pk)]
            seller_product.save()

    def get_product_quantity(self, seller_product):
        return self.quantity_products.get(str(seller_product.pk))


class OrderStatus(models.Model):
    class Meta:
        verbose_name = 'статус заказа'
        verbose_name_plural = 'статусы заказа'

    value = models.CharField(null=True, max_length=256, verbose_name='значение')
    name = models.CharField(max_length=256, verbose_name='название')

    def __str__(self):
        return self.name

src/market/orders/forms.py
import re

from django import forms

from market.orders.models import Order


class AddErrorMixin:
    def clean(self):
        for field_name, field in self.fields.items():
            if field_name in self.errors.as_data():
                field.widget.attrs.update({'class': 'form-input form-input_error'})

        return super().clean()


class OrderCreationPage1Form(forms.ModelForm, AddErrorMixin):
    class Meta:
        model = Order
        fields = 'full_name', 'phone', 'email'

    full_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-input', 'id': 'name'}),
        label='ФИО',
    )
    phone = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': '+7 (___) _______', 'id': 'phone'}),
        label='Телефон',
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-input', 'id': 'mail'}),
        label='E-mail',
    )

    def clean_full_name(self):
        data = self.cleaned_data['full_name']
        split_data = data.split()
        if not ''.join(split_data).isalpha():
            self.add_error('full_name', 'Это поле может содержать только буквы и пробелы')
        if len(split_data) != 3:
            self.add_error('full_name', 'Это поле должно состоять из 3-х слов')
        return data

    def clean_phone(self):
        data = self.cleaned_data['phone']
        if re.fullmatch(r'\+7 \(\d{3}\) \d{7}', data) is None:
            self.add_error('phone', 'Номер должен состоять из кода региона и 10 цифр')
        return data


class OrderCreationPage2Form(forms.ModelForm, AddErrorMixin):
    class Meta:
        model = Order
        fields = 'delivery_city', 'delivery_address', 'delivery_method'
        widgets = {
            'delivery_method': forms.RadioSelect()
        }

    delivery_city = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-input'}),
        label='Город',
    )
    delivery_address = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-input'}),
        label='Адрес',
    )


class OrderCreationPage3Form(forms.ModelForm, AddErrorMixin):
    class Meta:
        model = Order
        fields = 'payment_method',
        widgets = {
            'payment_method': forms.RadioSelect()
        }

src/market/orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, reverse
from django.core.cache import cache
from django.views.generic import FormView, TemplateView, ListView, DetailView
from django.urls import reverse_lazy

from rest_framework.viewsets import ModelViewSet

from .forms import OrderCreationPage1Form, OrderCreationPage2Form, OrderCreationPage3Form
from .models import Order, OrderStatus
from .serializers import OrderSerializer
from .tasks import order_created
from ..cart.cart import Cart
from ..cart.rebuild_cart import create_json_cart
from ..categories.mixins import MenuMixin
from ..search_app.forms import SearchForm
from ..search_app.mixins import SearchMixin
from ..sellers.models import DiscountType


class OrdersHistoryView(LoginRequiredMixin, ListView, MenuMixin, SearchMixin):
    template_name = 'orders/orders_history.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user).select_related('status').order_by('-created_at')


class OrderDetailView(LoginRequiredMixin, DetailView, MenuMixin, SearchMixin):
    template_name = 'orders/order_details.html'
    queryset = Order.objects.select_related('status').prefetch_related(
        'seller_products__product',
        'seller_products__discount',
    )
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = context.get('order')
        context['seller_products_and_quantity'] = [
            (seller_product, order.get_product_quantity(seller_product))
            for seller_product in order.get_products()
        ]
        return context


class OrderViewSet(ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer


class MakingOrderTemplateViewMixin(MenuMixin, TemplateView):
    template_name = 'orders/making_an_order.html'
    search_form = SearchForm


class CheckUserCacheMixin(UserPassesTestMixin):
    current_page = None

    def test_func(self):
        form_cache = cache.get(f'order_create_{self.request.user.id}')
        if not form_cache:
            form_cache = dict()

        if not form_cache or form_cache['current_page'] < self.page:
            self.current_page = form_cache.get('current_page', 1)
            return False

        return True

    def handle_no_permission(self):
        return redirect(f'orders:making_an_order_page_{self.current_page}')


class MakingOrderViewMixin(SearchMixin, LoginRequiredMixin, MakingOrderTemplateViewMixin, FormView):
    success_url = reverse_lazy('orders:making_an_order')
    page = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        form_cache = cache.get(f'order_create_{self.request.user.id}')
        if form_cache:
            form_data = form_cache.get(f'form_{self.page}')
            if form_data:
                form = self.form_class(form_data)
                context['form'] = form
        else:
            form_cache = dict()

            # предзаполнение данных пользователя
            user = self.request.user
            user_profile = self.request.user.profile
            form = self.form_class({
                'full_name': user_profile.full_name,
                'phone': user_profile.phone,
                'email': user.email,
            })
            context['form'] = form

        context['current_page'] = form_cache.get('current_page', 1)
        context['page'] = self.page
        return context

    def post(self, request, *args, **kwargs):
        response = super().post(request, *args, **kwargs)
        if response:
            return response

        form = self.form_class(request.POST)
        if form.is_valid():
            form_cache = cache.get(f'order_create_{self.request.user.id}')
            if form_cache:
                form_cache[f'form_{self.page}'] = form.cleaned_data
                if self.page == form_cache.get('current_page'):
                    form_cache['current_page'] += 1
            else:
                form_cache = {
                    f'form_{self.page}': form.cleaned_data,
                    'current_page': self.page + 1,
                }

            cache.set(f'order_create_{self.request.user.id}', form_cache, 3600)

            return redirect(f'orders:making_an_order_page_{self.page + 1}')

        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)


class MakingOrderPage1View(MakingOrderViewMixin):
    form_class = OrderCreationPage1Form
    success_url = reverse_lazy('orders:making_an_order_page_2')
    page = 1


class MakingOrderPage2View(CheckUserCacheMixin, MakingOrderViewMixin):
    form_class = OrderCreationPage2Form
    success_url = reverse_lazy('orders:making_an_order_page_3')
    page = 2


class MakingOrderPage3View(CheckUserCacheMixin, MakingOrderViewMixin):
    form_class = OrderCreationPage3Form
    success_url = reverse_lazy('orders:making_an_order_page_4')
    page = 3


class MakingOrderPage4View(SearchMixin, CheckUserCacheMixin, MakingOrderTemplateViewMixin):
    page = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        form_cache = cache.get(f'order_create_{self.request.user.id}')
        forms = {
            'form_1': OrderCreationPage1Form(form_cache['form_1']),
            'form_2': OrderCreationPage2Form(form_cache['form_2']),
            'form_3': OrderCreationPage3Form(form_cache['form_3']),
        }

        context.update({
            'page': self.page,
            'current_page': form_cache.get('current_page'),
            'forms': forms,
        })
        return context

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        response = super().post(request, *args, **kwargs)
        if response:
            return response

        form_data = cache.get(f'order_create_{request.user.id}')
        if not form_data:
            return redirect('orders:making_an_order_page_1')

        form_1, form_2, form_3 = (value for key, value in form_data.items() if key.startswith('form_'))

        # создание заказа
        cart = Cart(request.session)
        not_paid_order_status = OrderStatus.objects.get(value='not_paid')
        discount_type = DiscountType.objects.get(name=cart.get_priority_discount_type())
        order = Order.objects.create(
            user=request.user,
            full_name=form_1['full_name'],
            phone=form_1['phone'],
            email=form_1['email'],
            delivery_city=form_2['delivery_city'],
            delivery_address=form_2['delivery_address'],
            delivery_method=form_2['delivery_method'],
            payment_method=form_3['payment_method'],
            status=not_paid_order_status,
            cost=cart.get_priority_discounted_cost(),
            discount_type=discount_type,
            quantity_products=create_json_cart(cart),
        )

        # добавление в заказ продуктов из корзины
        order.seller_products.set(cart.cart.keys())

        cart.clear()
        # запустить асинхронное задание
        order_created.delay(order.id)
        cache.delete(f'order_create_{self.request.user.id}')

        return redirect(reverse('payment:payment', kwargs={'pk': order.pk}))

src/market/orders/templates/orders/making_an_order_base.html
{% extends 'repeat_blocks.html' %}
{% load static %}

{% block title %}
  <title>Создание заказа</title>
{% endblock %}

{% block header-slider %}
{% endblock %}

{% block additional_link_script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="{% static 'assets/js/jquery.maskedinput.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'assets/css/making_an_order.css' %}">
{% endblock %}

{% block middle %}
  <div class="Section Section_column Section_columnRight Section_columnWide Order">
    <div class="wrap">
      <div class="Section-column">
        <div class="Section-columnSection">
          <header class="Section-header">
            <strong class="Section-title">Прогресс заполнения</strong>
          </header>
          <div class="Section-columnContent">
            <div class="NavigateProfile">
              <ul class="menu menu_vt">
                <li class="{% if page == 1 %}menu-item_ACTIVE{% endif %} menu-item"><a href="{% url 'orders:making_an_order_page_1' %}" class="menu-link {% if 1 > current_page %}menu-link-disabled{% endif %}">Шаг 1. Параметры пользователя</a></li>
                <li class="{% if page == 2 %}menu-item_ACTIVE{% endif %} menu-item"><a href="{% url 'orders:making_an_order_page_2' %}" class="menu-link {% if 2 > current_page %}menu-link-disabled{% endif %}">Шаг 2. Способ доставки</a></li>
                <li class="{% if page == 3 %}menu-item_ACTIVE{% endif %} menu-item"><a href="{% url 'orders:making_an_order_page_3' %}" class="menu-link {% if 3 > current_page %}menu-link-disabled{% endif %}">Шаг 3. Способ оплаты</a></li>
                <li class="{% if page == 4 %}menu-item_ACTIVE{% endif %} menu-item"><a href="{% url 'orders:making_an_order_page_4' %}" class="menu-link {% if 4 > current_page %}menu-link-disabled{% endif %}">Шаг 4. Подтверждение заказа</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="Section-content">
        {% block form %}

        {% endblock %}
      </div>
    </div>
  </div>
  <script>
      $('#phone').mask('+7 (999) 9999999', {autoclear: false});
  </script>
{% endblock %}

src/market/orders/templates/orders/order_details.html
{% extends 'repeat_blocks.html' %}
{% load static %}
{% load cart_filters %}

{% block title %}
  <title>Заказ</title>
{% endblock %}

{% block header-slider %}

{% endblock %}

{% block middle %}
  <div class="Middle-top">
    <div class="wrap">
      <div class="Middle-header">
        <h1 class="Middle-title">Заказ №{{ order.pk }}
        </h1>
      </div>
    </div>
  </div>
  <div class="Section">
    <div class="wrap">
      <div class="Section-content">
        <div class="Orders">
        </div>
        <div class="Order">
          <div class="Order-infoBlock">
            <div class="Order-personal">
              <div class="row">
                <div class="row-block">
                  <div class="Order-info Order-info_date">
                    <div class="Order-infoType">Дата заказа:
                    </div>
                    <div class="Order-infoContent">{{ order.created_at|date:'d.m.Y' }}
                    </div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">ФИО:
                    </div>
                    <div class="Order-infoContent">{{ order.full_name }}
                    </div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">Телефон:
                    </div>
                    <div class="Order-infoContent">{{ order.phone }}
                    </div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">E-mail:
                    </div>
                    <div class="Order-infoContent">{{ order.email }}
                    </div>
                  </div>
                </div>
                <div class="row-block">
                  <div class="Order-info Order-info_delivery">
                    <div class="Order-infoType">Тип доставки:
                    </div>
                    <div class="Order-infoContent">{{ order.get_delivery_method_display }}
                    </div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">Город:
                    </div>
                    <div class="Order-infoContent">{{ order.delivery_city }}
                    </div>
                  </div>
                  <div class="Order-info">
                    <div class="Order-infoType">Адрес:
                    </div>
                    <div class="Order-infoContent">{{ order.delivery_address }}
                    </div>
                  </div>
                  <div class="Order-info Order-info_pay">
                    <div class="Order-infoType">Оплата:
                    </div>
                    <div class="Order-infoContent">{{ order.get_payment_method_display }}
                    </div>
                  </div>
                  <div class="Order-info Order-info_status">
                    <div class="Order-infoType">Статус:
                    </div>
                    <div class="Order-infoContent">{{ order.status.name }}
                    </div>
                  </div>
                  {% if not order.check_paid %}
                    <div class="Order-info Order-info_error">
                      <div class="Order-infoType">Оплата не прошла:
                      </div>
                      <div class="Order-infoContent">Оплата не выполнена
                      </div>
                    </div>
                  {% endif %}
                </div>
              </div>
            </div>
            <div class="Cart Cart_order">
              {% for seller_product, quantity in seller_products_and_quantity %}
                <div class="Cart-product">
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_pict">
                      <a class="Cart-pict" href="{% url 'products:product-details' product_slug=seller_product.product.slug %}"><img class="Cart-img" src="{{ seller_product.product.preview.url }}" alt="card.jpg"/>
                      </a>
                    </div>
                    <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{% url 'products:product-details' product_slug=seller_product.product.slug %}">{{ seller_product.product.name }}</a>
                      <div class="Cart-desc">Это супер ноутбук, 3 гб. 4 ядра
                      </div>
                    </div>
                    <div class="Cart-block Cart-block_price">
                      <div class="Cart-price">
                        {% if order.discount_type.name == 'products_discount' and seller_product.discount.value > 0 %}
                          {{ seller_product.get_discounted_price|mul_price:quantity }} руб.
                        {% else %}
                          {{ seller_product.price|mul_price:quantity }} руб.
                        {% endif %}
                      </div>
                    </div>
                  </div>
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_amount">{{ quantity }} шт.
                    </div>
                  </div>
                </div>
              {% endfor %}
              <div class="Cart-total">
                <div class="Cart-block Cart-block_total">
                  <strong class="Cart-title">Итого:<span class="Cart-price">{{ order.cost }} руб.</span>
                  </strong>
                </div>
                {% if not order.check_paid %}
                  <div class="Cart-block"><a class="btn btn_primary btn_lg" href="{% url 'payment:payment' pk=order.pk %}">Оплатить</a>
                {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

src/market/orders/templates/orders/orders_history.html
{% extends 'repeat_blocks.html' %}

{% block title %}
  <title>История заказов</title>
{% endblock %}

{% block header-slider %}

{% endblock %}

{% block middle %}
  <div class="Section Section_column Section_columnLeft">
    <div class="wrap">
      <div class="Section-column">
        <div class="Section-columnSection">
          <header class="Section-header">
            <strong class="Section-title">Навигация
            </strong>
          </header>
          <div class="Section-columnContent">
            <div class="NavigateProfile">
              <ul class="menu menu_vt">
                <li class="menu-item"><a class="menu-link" href="{% url 'market.profiles:account' %}">Личный кабинет</a>
                </li>
                <li class="menu-item"><a class="menu-link" href="{% url 'market.profiles:profile' %}">Профиль</a>
                </li>
                <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'orders:orders_history' %}">История заказов</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="Section-content">
        <div class="Orders">
          {% if not orders %}
            У вас нет заказов
          {% endif %}
          {% for order in orders %}
            <div class="Order Order_anons">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block"><a class="Order-title" href="{% url 'orders:order_details' pk=order.pk %}">Заказ&#32;<span class="Order-numberOrder">№{{ order.pk }}</span>&#32;от&#32;<span class="Order-dateOrder">{{ order.created_at|date:'d.m.Y' }}</span></a>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">Тип доставки:
                      </div>
                      <div class="Order-infoContent">{{ order.get_delivery_method_display }}
                      </div>
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">Оплата:
                      </div>
                      <div class="Order-infoContent">{{ order.get_payment_method_display }}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Общая стоимость:
                      </div>
                      <div class="Order-infoContent"><span class="Order-price">{{ order.cost }} руб.</span>
                      </div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">Статус:
                      </div>
                      <div class="Order-infoContent">{{ order.status }}
                      </div>
                    </div>
                    {% if not order.check_paid %}
                      <div class="Order-info Order-info_error">
                        <div class="Order-infoType">Оплата не прошла:
                        </div>
                        <div class="Order-infoContent">Оплата не выполнена
                        </div>
                      </div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}